### ISSUE TITLE
Create Commander Alias not working yet

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/core-commander#1]
**Describe the bug**
Create Commander Alias does not work yet.

**To Reproduce**

bash commander.sh

Enter M

    ===============================================================

    U. Install OS Updates
    E. Create Commander Executable
    A. Create Commander Alias

    ===============================================================

    H. Show Help

    ===============================================================

    X. Back to Main Menu

    ===============================================================

    Please enter your choice: A
/home/jarunik/core-commander/menus/miscellaneous/args.sh: line 21: miscellaneous_commander_alias: command not found
    Press any key to continue

**Expected behavior**
I guess there should be an implementation to create a bash file.

**Screenshots**

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04

**Additional context**
n/a

**Comment by Jarunik** [comment]
Create Commander Alias (A)
lets you create alias so you can start Commander by inputting “commander” instead of “bash ./commander.sh” from anywhere within your.

If someone looks at it ... the text is also missing something... anywhere within your [?] 

Maybe shell?

**Comment by faustbrian** [comment]
Should be fixed by https://github.com/ArkEcosystem/core-commander/commit/37a347680a4630bd23883209b548735d90ff241d.

Opened an issue for the help.sh files to be improved by a native english speaker https://github.com/ArkEcosystem/core-commander/issues/2

Out for today 🚀

**Comment by reConNico** [comment]
@faustbrian : Shouldn't we add `source ${HOME}/.bashrc` to the `miscellaneous_commander_alias` function as well to make sure it register the command instantly?

**Comment by faustbrian** [comment]
It already does here https://github.com/ArkEcosystem/core-commander/blob/master/actions/miscellaneous/alias.sh#L8.

`source` and `.` mean the same thing but `.` is a POSIX standard and more widely supported.
