### ISSUE TITLE
Commander not setting custom ENV variables (eg. ARK_DB_USERNAME) and uses defaults

### ISSUE THREAD

**Issue by roks0n** [ArkEcosystem/core-commander#15]
**Describe the bug**
When installing node using `commander` it created a database user using $USER (which is the current user and is also set as an ENV var).

The problem occurs when we start the `core` it tries to get a user from ENV var using `ARK_DB_USERNAME` which is not set by the `commander`.

This causes the following error when starting a node:
```
error: Unable to connect to the database SequelizeConnectionError: password authentication failed for user "ark"
```

**To Reproduce**
1. don't user `ark` as the user on the server
2. run commander and start the installation
3. start a relay node
4. check the relay node's logs
5. you'll see the error msgs

**Expected behavior**
The commander should set all necessary environment variables needed by the node, especially if they are customizable by the user.

Env variables can be set to `~/.bashrc` but this might not be reliable especially if a certain OS doesn't pick up env variables from here. Might be better to create `.env` file in `core` directory or `~/.ark/config` and pass it along when starting the node.

**Screenshots**
n/a

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04

**Additional context**
n/a

**Comment by faustbrian** [comment]
The easiest is to create a `~/.ark/.env` file which will be automatically loaded by the container https://github.com/ArkEcosystem/core/blob/master/packages/core-container/lib/environment.js#L72 before any plugins are loaded.

Would probably be good to add a menu where you can set the env variables for that file.
