### ISSUE TITLE
Actions in submenu exit to main menu

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/core-commander#23]
**Describe the bug**
When managing Relay, start/restart/logs, exits to main menu.

**To Reproduce**
1. Manage Relay
2. Start Relay
3. Jumps back to main menu
4. Manage Relay
5. See Logs
Goto 3.

**Expected behavior**
Upon exit from Relay operation, the menu should stay in the Relay section, not exit back to main menu.

**Comment by reConNico** [comment]
I don't think that needs to be changed. I like the workflow that it goes back to main menu because you've finished your "managing" and want to see your node status.

**Comment by vRobM** [comment]
The point; is that I have not finished my "managing" and I want to continue, but I am not allowed and forced to "re-manage" every time.

Makes for poor UX and jumping to conclusions
