### ISSUE TITLE
Reason for updatedb?

### ISSUE THREAD

**Issue by supaiku0** [ArkEcosystem/core-commander#33]
Hi,

I'm just wondering why the commander calls `sudo updatedb` when started. I cannot find any use of `locate` so `updatedb` is kinda pointless unless I missed something.

If updatedb is not needed, I would like to remove it. Otherwise I need to know where it is being used, so I can remove the `sudo` call by pointing all `locate`s to a `$HOME` database.

**Comment by faustbrian** [comment]
Just a remnant of the previous commander, can be removed.
