### ISSUE TITLE
Error in Installation of v2 explorer

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/core-commander#49]
**Describe the bug**
Error in installation log for explorer.

**To Reproduce**
Install explorer with commander

**Expected behavior**
No errors in the log

**Screenshots**
n/a

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version e.g. 18.04

**Additional context**

    ==> Installing ARK Explorer...
Cloning into '/home/jarunik/ark-explorer'...
remote: Counting objects: 11035, done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 11035 (delta 19), reused 21 (delta 7), pack-reused 10980
Receiving objects: 100% (11035/11035), 8.47 MiB | 24.56 MiB/s, done.
Resolving deltas: 100% (7138/7138), done.
    ==> Installing dependencies...
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jest > jest-cli > istanbul-api > istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
warning nightwatch > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-plugin-vue@4.7.1" has incorrect peer dependency "eslint@^3.18.0 || ^4.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 53.05s.
    ==> Installed dependencies!
    ==> Building...
yarn run v1.9.4
$ node build/build.js --network devnet
⠋ building for production...Will use the arguments: host: '-', port: '-', baseUrl: '/', network: 'devnet', routerMode: 'hash'
⠸ building for production...Killed
**error Command failed with exit code 137.**
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ==> Building!
    ==> Installed ARK Explorer!

**Comment by dated** [comment]
iirc 137 stands for an out of memory error.

**Comment by Jarunik** [comment]
Ok. Will try with bigger RAM box. :-)

**Comment by Jarunik** [comment]
Maybe we should somewhere indicate how much you need for explorer?

**Comment by dated** [comment]
And error handling. `==> Installed ARK Explorer!` is obviously not correct in this case.

**Comment by Jarunik** [comment]
4GB RAM worked. :-)
