### ISSUE TITLE
ark-core configuration

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core-commander#54]
**Describe the bug**
Missing default values when configuring ark-core.

**To Reproduce**
<img width="856" alt="screen shot 2018-09-21 at 23 41 48" src="https://user-images.githubusercontent.com/3462869/45905178-1fed8900-bdf8-11e8-8913-b76a4914fdb9.png">

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 16.04]

**Additional context**

**Comment by faustbrian** [comment]
I am unable to reproduce this based on the information you provided, everything is working as intended.

**Comment by zillionn** [comment]
A. Manage Ark Core -> D. Configure Database
If the `ARK_DB_` lines in the `~/.ark/.env` file exist, the Commander will change them, but if they're missing, it will not add them. I believe the Commander is adding them only when creating the `~/.ark/.env` file.
