### ISSUE TITLE
Ark Commander updates the core but does not update the plugins.js

### ISSUE THREAD

**Issue by vaustymenko** [ArkEcosystem/core-commander#71]
Describe the bug
Ark Commander offers to update the core but it does not update the ~/.ark/plugins.js. As a result, if modules are removed in the core then relay/forger fail to start because they cannot find modules

To Reproduce

Launch Ark Commande
Select options to update core
Restart relay and observe logs
I saw things like
1|ark-core-relay | Error: Cannot find module '@arkecosystem/core-transaction-pool-redis'
1|ark-core | Error: Cannot find module '@arkecosystem/core-storage'
Expected behavior
Ark Commander must update the plugins.js, otherwise there is no point in updating the core

**Comment by vaustymenko** [comment]
Comment from @faustbrian:
-----------------------------
The plugins.js doesn't get updated because it can be touchy to do so, both because of people running modified configurations and having 3rd party plugins installed.

You as a node maintainer should know what runs on your server and what configuration is getting modified, it is also your responsibility as the maintainer to make sure your config is up to date with the latest changes as you shouldn't blindly update.

Also this issue should go to https://github.com/ArkEcosystem/core-commander

**Comment by vaustymenko** [comment]
I do agree that any custom configuration will be overwritten.

But, you have to consider the main use case for "regular" node maintainers: 
1) they do not have custom configs
2) they want to do periodic updates of the core
3) they do not know what new dependencies come with core updates and what dependencies get dropped

I would suggest that the Commander has to update the plugins.js but before the update ask user to backup plugins.js in case they have any custom changes there

**Comment by fix** [comment]
Is there a way to somehow detected if the plug-in has been touched? Some sha256 of the file when there is a need for migration?

And then warn in the console if the config has been touched and should be updated with detailed info?

**Comment by boldninja** [comment]
Hm one option could be:

Compare SHA256 of previous default plugins.js file in core repo (eg. https://github.com/ArkEcosystem/core/blob/develop/packages/core/lib/config/mainnet/plugins.js )  with new one (once update is avail) and if SHA256 match don't do anything, if there was an update to default plugins.js file see the SHA256 of users local plugins.js.

If SHA256 is same as the one from before update means he is using default config so can be replaced?
If SHA256 differs from before the update means its either modified or running even older version (at least 2 versions back) in that case notify that user's plugin.js file is either a lot older or its been modified by the user. If he wants to update needs to confirm and take the risks (makes a backup of old one as backup)?

I don't see other options here, in any case this is user file and shouldn't just be replaced without some kind of information to the user.
