### ISSUE TITLE
Explorer

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core-commander#85]
I don't recall installing the Explorer but I got it somehow:

<img width="605" alt="screen shot 2018-11-12 at 15 18 59" src="https://user-images.githubusercontent.com/3462869/48349948-5f18b780-e68e-11e8-838f-c9be28888264.png">

How to uninstall it?

**Comment by dated** [comment]
type `P` and hit enter, it should work even if not shown. fixing now.
